import { useState, type FormEvent } from 'react'
import { useAssignments } from '../hooks/useAssignments'
import { academicApi } from '../services/academicApi'
import type { AssignmentInput, Priority } from '../types/academic'
import { derivedAssignmentStatus, displayDateTime, toIsoDateTime } from '../utils/academicDates'
import { Button, DataState, Icon, LoadingCards, PageIntro, PriorityBadge, VerifyBadge } from '../components/academic/ui'
import './academic-pages.css'

const emptyDraft = (): AssignmentInput => ({ title: '', subject_id: '', priority: 'medium', description: '', due_at: null, estimated_minutes: null })
export function AssignmentsPage() {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [priority, setPriority] = useState(''); const [showEditor, setShowEditor] = useState(false); const [draft, setDraft] = useState<AssignmentInput>(emptyDraft); const [formError, setFormError] = useState(''); const [saving, setSaving] = useState(false); const [actionError, setActionError] = useState('')
  const { data, loading, error, refresh } = useAssignments({ search, status, priority, sort: 'due_date', page_size: 50 })
  const submit = async (event: FormEvent) => { event.preventDefault(); setFormError(''); if (!draft.title.trim()) return setFormError('A title is required.'); if (!draft.subject_id.trim()) return setFormError('Choose a subject from your verified enrolment.'); setSaving(true); try { await academicApi.createAssignment({ ...draft, title: draft.title.trim(), due_at: draft.due_at || null }); setShowEditor(false); setDraft(emptyDraft()); refresh() } catch (cause) { setFormError(cause instanceof Error ? cause.message : 'Could not save the assignment.') } finally { setSaving(false) } }
  const changeStatus = async (id: string, next: 'completed' | 'not_started') => { setActionError(''); try { await academicApi.setAssignmentStatus(id, next); refresh() } catch (cause) { setActionError(cause instanceof Error ? cause.message : 'Could not update this assignment.') } }
  return <>
    <PageIntro title="Assignments" eyebrow="ACADEMIC WORKSPACE" action={<Button icon="plus" onClick={() => { setFormError(''); setShowEditor(true) }}>Add personal assignment</Button>}>Track coursework from verified faculty records and your own confirmed tasks.</PageIntro>
    <section className="filter-bar"><label className="search-control"><Icon name="checklist" size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search assignments" aria-label="Search assignments" /></label><label className="select-control"><span className="sr-only">Filter by status</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option><option value="not_started">Not started</option><option value="in_progress">In progress</option><option value="completed">Completed</option></select></label><label className="select-control"><span className="sr-only">Filter by priority</span><select value={priority} onChange={(event) => setPriority(event.target.value)}><option value="">All priorities</option><option value="urgent">Urgent</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><Button kind="quiet" icon="refresh" onClick={refresh}>Refresh</Button></section>
    {actionError && <div className="form-alert">{actionError}</div>}
    {loading && <LoadingCards count={3} />}
    {!loading && !data && <DataState error={error} onRetry={refresh} itemName="assignments" />}
    {!loading && data && (data.items.length === 0 ? <DataState itemName="assignments">Add a personal task or wait for a verified assignment to be published to your enrolled subjects.</DataState> : <section className="records-panel"><div className="records-head"><span>{data.total} assignment{data.total === 1 ? '' : 's'}</span><span>Sorted by nearest deadline</span></div><div className="assignment-list">{data.items.map((item) => { const currentStatus = derivedAssignmentStatus(item); return <article className={`assignment-row ${currentStatus === 'completed' ? 'is-complete' : ''}`} key={item.id}><button className={`check-button ${currentStatus === 'completed' ? 'checked' : ''}`} aria-label={currentStatus === 'completed' ? 'Reopen assignment' : 'Mark assignment complete'} disabled={!item.editable} onClick={() => { void changeStatus(item.id, currentStatus === 'completed' ? 'not_started' : 'completed') }}><Icon name="check" size={15} /></button><div className="assignment-main"><div className="assignment-title"><strong>{item.title}</strong><PriorityBadge priority={item.priority} />{currentStatus === 'overdue' && <span className="overdue">Overdue</span>}</div><div className="assignment-meta"><span><Icon name="book" size={13} />{item.subject?.title || 'Subject not returned'}</span>{item.due_at && <span><Icon name="clock" size={13} />Due {displayDateTime(item.due_at)}</span>}{item.estimated_minutes !== null && item.estimated_minutes !== undefined && <span>{item.estimated_minutes} min planned</span>}</div></div><div className="assignment-side"><VerifyBadge status={item.verification_status} /><button className="row-menu" aria-label={`More options for ${item.title}`}><Icon name="dots" size={19} /></button></div></article> })}</div></section>)}
    {showEditor && <div className="modal-backdrop" role="presentation"><section className="editor-modal" role="dialog" aria-modal="true" aria-labelledby="assignment-dialog-title"><div className="modal-heading"><div><span className="panel-kicker">PERSONAL WORK</span><h2 id="assignment-dialog-title">Add an assignment</h2></div><button className="modal-close" aria-label="Close" onClick={() => setShowEditor(false)}><Icon name="close" size={19} /></button></div><form onSubmit={submit}><label>Title<input autoFocus value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} maxLength={160} /></label><label>Subject ID<span className="field-hint">Use an ID from your verified subject enrolment.</span><input value={draft.subject_id} onChange={(event) => setDraft({ ...draft, subject_id: event.target.value })} /></label><div className="form-grid"><label>Due date & time<input type="datetime-local" value={draft.due_at ? new Date(draft.due_at).toISOString().slice(0, 16) : ''} onChange={(event) => setDraft({ ...draft, due_at: toIsoDateTime(event.target.value) })} /></label><label>Priority<select value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: event.target.value as Priority })}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></label></div><label>Estimated minutes<input min="0" type="number" value={draft.estimated_minutes ?? ''} onChange={(event) => setDraft({ ...draft, estimated_minutes: event.target.value ? Number(event.target.value) : null })} /></label><label>Description<textarea rows={3} value={draft.description || ''} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label>{formError && <div className="form-alert">{formError}</div>}<div className="modal-actions"><Button kind="secondary" type="button" onClick={() => setShowEditor(false)}>Cancel</Button><Button type="submit" icon="plus" disabled={saving}>{saving ? 'Saving…' : 'Save assignment'}</Button></div></form></section></div>}
  </>
}
