import { useState } from 'react'
import { useAttendance } from '../hooks/useAttendance'
import { academicApi } from '../services/academicApi'
import type { AttendanceSimulation } from '../types/academic'
import { displayDateTime } from '../utils/academicDates'
import { Button, DataState, Icon, LoadingCards, PageIntro, RiskBadge, VerifyBadge } from '../components/academic/ui'
import './academic-pages.css'

export function AttendancePage() {
  const { data, loading, error, refresh } = useAttendance(); const [selected, setSelected] = useState(''); const [futureClasses, setFutureClasses] = useState(1); const [action, setAction] = useState<'attend' | 'miss'>('attend'); const [simulation, setSimulation] = useState<AttendanceSimulation | null>(null); const [simError, setSimError] = useState(''); const [simulating, setSimulating] = useState(false)
  const subjectId = selected || data?.subjects[0]?.subject.id || ''
  const simulate = async () => { if (!subjectId || futureClasses < 1) return; setSimulating(true); setSimError(''); try { setSimulation(await academicApi.attendanceWhatIf(subjectId, futureClasses, action)) } catch (cause) { setSimError(cause instanceof Error ? cause.message : 'Could not calculate that simulation.') } finally { setSimulating(false) } }
  return <>
    <PageIntro title="Attendance" eyebrow="ACADEMIC WORKSPACE" action={<Button kind="secondary" icon="refresh" onClick={refresh}>Refresh attendance</Button>}>Your attendance is calculated from verified records. Simulations never change those records.</PageIntro>
    {loading && <LoadingCards count={3} />}
    {!loading && !data && <DataState error={error} onRetry={refresh} itemName="attendance">Attendance will show after it is uploaded for your enrolled subjects.</DataState>}
    {!loading && data && (data.subjects.length === 0 ? <DataState itemName="attendance records">No attendance has been uploaded yet. A zero percentage is never shown when no classes have been held.</DataState> : <>
      <section className="attendance-overview"><article><span className="panel-kicker">WEIGHTED OVERALL ATTENDANCE</span><strong>{data.overall_percentage === null ? '—' : `${data.overall_percentage.toFixed(1)}%`}</strong><p>{data.overall_percentage === null ? 'No classes have been held yet.' : 'Based on total classes attended across all subjects.'}</p></article><div className="attendance-legend"><span><i className="dot safe"></i>Safe</span><span><i className="dot warning"></i>Near requirement</span><span><i className="dot critical"></i>Below requirement</span></div></section>
      <section className="attendance-table">{data.subjects.map((row) => <article key={row.subject.id} className="attendance-row"><div className="attendance-subject"><strong>{row.subject.title}</strong><span>{row.subject.code || 'Enrolled subject'}</span></div><div className="attendance-numbers"><span>Attended <strong>{row.attended_classes}</strong></span><span>Held <strong>{row.held_classes}</strong></span></div><div className="attendance-percent"><strong>{row.percentage === null ? '—' : `${row.percentage.toFixed(1)}%`}</strong><span>Minimum {row.minimum_required_percentage === null ? 'not set' : `${row.minimum_required_percentage}%`}</span></div><RiskBadge risk={row.risk} /><div className="attendance-verified"><VerifyBadge status={row.verification_status} />{row.last_updated_at && <small>Updated {displayDateTime(row.last_updated_at)}</small>}</div></article>)}</section>
      <section className="simulator-panel"><div className="simulator-copy"><span className="panel-kicker">WHAT-IF SIMULATOR</span><h2>Plan your next classes</h2><p>See the deterministic result before you decide. It is not saved as attendance.</p></div><div className="simulator-controls"><label>Subject<select value={subjectId} onChange={(event) => { setSelected(event.target.value); setSimulation(null) }}>{data.subjects.map((row) => <option value={row.subject.id} key={row.subject.id}>{row.subject.title}</option>)}</select></label><label>Future classes<input type="number" min="1" max="500" value={futureClasses} onChange={(event) => setFutureClasses(Math.max(1, Number(event.target.value) || 1))} /></label><label>Scenario<select value={action} onChange={(event) => setAction(event.target.value as 'attend' | 'miss')}><option value="attend">Attend them</option><option value="miss">Miss them</option></select></label><Button icon="target" onClick={() => { void simulate() }} disabled={simulating}>{simulating ? 'Calculating…' : 'Calculate'}</Button></div>{simError && <div className="form-alert">{simError}</div>}{simulation && <div className="simulation-result"><span className="sim-badge"><Icon name="spark" size={15} />Simulation only</span><strong>{simulation.simulated_percentage === null ? 'Not available' : `${simulation.simulated_percentage.toFixed(1)}%`}</strong><p>Current: {simulation.current_percentage === null ? 'not available' : `${simulation.current_percentage.toFixed(1)}%`} · {simulation.recovery_classes === null ? 'Recovery calculation unavailable' : `${simulation.recovery_classes} class(es) to reach target`} · {simulation.safe_misses === null ? 'Safe-miss calculation unavailable' : `${simulation.safe_misses} safe miss(es)`}</p><RiskBadge risk={simulation.risk} /><button onClick={() => setSimulation(null)}>Reset</button></div>}</section>
    </>)}
  </>
}
