import { useState, type FormEvent } from 'react'
import { useReminders } from '../hooks/useReminders'
import { academicApi } from '../services/academicApi'
import type { ReminderInput } from '../types/academic'
import { displayDateTime, studentTimezone, toIsoDateTime } from '../utils/academicDates'
import { Button, DataState, Icon, LoadingCards, PageIntro, VerifyBadge } from '../components/academic/ui'
import './academic-pages.css'

const blank = (): ReminderInput => ({ title: '', description: '', scheduled_at: '', timezone: studentTimezone(), source_entity_type: 'personal' })
export function RemindersPage() {
  const [status, setStatus] = useState(''); const [showEditor, setShowEditor] = useState(false); const [draft, setDraft] = useState<ReminderInput>(blank); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState(''); const [actionError, setActionError] = useState('')
  const { data, loading, error, refresh } = useReminders({ status, page_size: 50 })
  const submit = async (event: FormEvent) => { event.preventDefault(); setFormError(''); if (!draft.title.trim()) return setFormError('A title is required.'); if (!draft.scheduled_at) return setFormError('Choose when the reminder should be scheduled.'); setSaving(true); try { await academicApi.createReminder({ ...draft, title: draft.title.trim() }); setDraft(blank()); setShowEditor(false); refresh() } catch (cause) { setFormError(cause instanceof Error ? cause.message : 'Could not save the reminder.') } finally { setSaving(false) } }
  const complete = async (id: string) => { setActionError(''); try { await academicApi.completeReminder(id); refresh() } catch (cause) { setActionError(cause instanceof Error ? cause.message : 'Could not update this reminder.') } }
  return <>
    <PageIntro title="Reminders" eyebrow="ACADEMIC WORKSPACE" action={<Button icon="plus" onClick={() => { setFormError(''); setShowEditor(true) }}>Add personal reminder</Button>}>Create personal prompts and follow linked academic records without duplicating the facts.</PageIntro>
    <section className="filter-bar"><label className="select-control"><span className="sr-only">Filter by status</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All reminders</option><option value="scheduled">Scheduled</option><option value="sent">Sent</option><option value="completed">Completed</option><option value="dismissed">Dismissed</option></select></label><span className="filter-spacer"></span><Button kind="quiet" icon="refresh" onClick={refresh}>Refresh</Button></section>{actionError && <div className="form-alert">{actionError}</div>}
    {loading && <LoadingCards count={3} />}
    {!loading && !data && <DataState error={error} onRetry={refresh} itemName="reminders" />}
    {!loading && data && (data.items.length === 0 ? <DataState itemName="active reminders">Personal reminders and confirmed academic reminders will appear here in chronological order.</DataState> : <section className="reminder-list">{data.items.map((item) => <article className={`reminder-card ${item.status === 'completed' ? 'reminder-complete' : ''}`} key={item.id}><div className="reminder-symbol"><Icon name={item.source_entity_type === 'personal' ? 'bell' : 'book'} size={19} /></div><div className="reminder-content"><div className="reminder-title"><strong>{item.title}</strong><span className={`reminder-status status-${item.status}`}>{item.status.replace('_', ' ')}</span></div>{item.description && <p>{item.description}</p>}<div className="reminder-meta"><span><Icon name="clock" size={13} />{displayDateTime(item.scheduled_at)}</span><span>{item.timezone}</span><span>{item.source_entity_type.replace('_', ' ')}</span></div></div><div className="reminder-actions"><VerifyBadge status={item.verification_status} />{item.editable && item.status !== 'completed' && <Button kind="secondary" onClick={() => { void complete(item.id) }} icon="check">Complete</Button>}</div></article>)}</section>)}
    <p className="privacy-note"><Icon name="spark" size={14} />AI suggestions must be confirmed before a reminder is created. Delivery scheduling belongs to the approved notification infrastructure.</p>
    {showEditor && <div className="modal-backdrop" role="presentation"><section className="editor-modal" role="dialog" aria-modal="true" aria-labelledby="reminder-dialog-title"><div className="modal-heading"><div><span className="panel-kicker">PERSONAL REMINDER</span><h2 id="reminder-dialog-title">Set a reminder</h2></div><button className="modal-close" aria-label="Close" onClick={() => setShowEditor(false)}><Icon name="close" size={19} /></button></div><form onSubmit={submit}><label>Title<input autoFocus value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} maxLength={160} /></label><label>When<input type="datetime-local" value={draft.scheduled_at ? new Date(draft.scheduled_at).toISOString().slice(0, 16) : ''} onChange={(event) => setDraft({ ...draft, scheduled_at: toIsoDateTime(event.target.value) || '' })} /></label><label>Description<textarea rows={3} value={draft.description || ''} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label><div className="timezone-note"><Icon name="clock" size={14} />The reminder will be stored in UTC and scheduled in {draft.timezone}.</div>{formError && <div className="form-alert">{formError}</div>}<div className="modal-actions"><Button kind="secondary" type="button" onClick={() => setShowEditor(false)}>Cancel</Button><Button type="submit" icon="bell" disabled={saving}>{saving ? 'Saving…' : 'Save reminder'}</Button></div></form></section></div>}
  </>
}
